DROP INDEX BOOS.PUBLISHER_PK;

CREATE TABLE BOOS.PUBLISHER 
(
  ID_PUB VARCHAR2(20 BYTE) NOT NULL 
, USERNAME VARCHAR2(100 BYTE) NOT NULL 
, PASSWORD VARCHAR2(100 BYTE) NOT NULL 
, NAME_OF_STORE VARCHAR2(150 BYTE) 
, PHONE VARCHAR2(20 BYTE) 
, ADDRESS VARCHAR2(100 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE UNIQUE INDEX BOOS.PUBLISHER_PK ON BOOS.PUBLISHER (ID_PUB ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX BOOS.PUBLISHER_PK ON BOOS.PUBLISHER (ID_PUB ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE BOOS.PUBLISHER
ADD CONSTRAINT PUBLISHER_PK PRIMARY KEY 
(
  ID_PUB 
)
USING INDEX BOOS.PUBLISHER_PK
ENABLE;
